# Lưu tài khoản/mật khẩu Admin

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: default # Đổi namespace nếu bạn dùng namespace khác
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"