apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-workflow-server-ingress
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/protocol: "https" # Vẫn giữ nguyên dòng này vì Argo dùng HTTPS nội bộ
    konghq.com/override: "argo-server-kong-config"
spec:
  ingressClassName: kong
  # ĐÃ XÓA ĐOẠN TLS Ở ĐÂY
  rules:
  - host: workflow.103.72.99.195.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-workflows-system-server
            port:
              number: 2746