apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-platform-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: cors-global # Áp dụng plugin CORS cho tất cả API
    # Gọi cert-manager cấp chứng chỉ SSL
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: kong
  
  # Cấu hình SSL cho domain nip.io
  tls:
  - hosts:
    - api.103.72.99.195.nip.io
    secretName: erp-platform-tls-secret
    
  rules:
  # Áp dụng domain nip.io cho tất cả các API bên dưới
  - host: api.103.72.99.195.nip.io
    http:
      paths:
      - path: /hr
        pathType: Prefix
        backend:
          service:
            name: hr-service
            port:
              number: 80

      - path: /organization
        pathType: Prefix
        backend:
          service:
            name: organization-service
            port:
              number: 80

      - path: /workflow
        pathType: Prefix
        backend:
          service:
            name: workflow-service
            port:
              number: 80

      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 80

      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 80

      - path: /config
        pathType: Prefix
        backend:
          service:
            name: config-server-service
            port:
              number: 8888

      - path: /user-activity
        pathType: Prefix
        backend:
          service:
            name: user-activity-service
            port:
              number: 80

      - path: /mail
        pathType: Prefix
        backend:
          service:
            name: mail-service
            port:
              number: 80