apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: remove-minio-iframe-block
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Bắt buộc đợi Kong cài xong
plugin: response-transformer
config:
  remove:
    headers:
    - X-Frame-Options
    - Content-Security-Policy
  add:
    headers:
    - "Content-Security-Policy: frame-ancestors 'self' *;"