apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-api
  template:
    metadata:
      labels:
        app: organization-api
    spec:
      containers:
      - name: organization-container
        image: dthieudocker/organization-service:05c856102968618eaa95dabb80bd5926a11c5820
        ports:
        - containerPort: 8080