apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "kong"
    # Quan trọng: Bảo Kong nói chuyện với ArgoCD bằng HTTP thường (vì đã có --insecure)
    konghq.com/protocol: "http" 
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - argo.103.72.99.195.nip.io
    secretName: argocd-server-tls
  rules:
  - host: argo.103.72.99.195.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80 # Đổi từ 443 sang 80 vì ArgoCD server giờ chạy mode insecure