apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-system
  namespace: argo-events
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-events.git
    targetRevision: stable
    path: manifests/namespace-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events # Bạn muốn cài vào đây
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - NamespaceAutoPropagation=true # Tự động đẩy namespace destination vào các resource con