apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo
spec:
  nats:
    native:
      replicas: 3 # Đảm bảo High Availability (Cần ít nhất 3 node, nếu chạy K3s 1 node thì đổi thành 1)
      auth: token