apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: grafana-webhook
  namespace: argo-events
spec:
  serviceAccountName: remediation-sa
  # THÊM ĐOẠN NÀY ĐỂ TẠO SERVICE
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    alert: 
      port: "12000"
      endpoint: /grafana
      method: POST