apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    targetRevision: 5.3.0
    chart: velero
    helm:
      values: |
        image:
          repository: velero/velero
          tag: v1.13.0

        # --- ĐÂY LÀ DÒNG QUYẾT ĐỊNH ---
        # Tắt cái Job tự động nâng cấp CRD đi. 
        # Helm 3 và ArgoCD vẫn sẽ tự động cài bộ CRD gốc cho bạn cực kỳ êm ái!
        upgradeCRDs: false 
        # -------------------------------

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: http://minio-service.default.svc.cluster.local:9000
        credentials:
          existingSecret: cloud-credentials
        deployNodeAgent: true
        snapshotsEnabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true