apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Cài cuối cùng để đảm bảo MinIO đã sống
spec:
  project: default
  source:
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    targetRevision: 5.3.0 # Tương đương Velero CLI v1.13
    chart: velero
    helm:
      values: |
        kubectl:
          image:
            repository: rancher/kubectl
            tag: "v1.30.0"
        
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: http://minio-service.default.svc.cluster.local:9000
        credentials:
          existingSecret: cloud-credentials
        deployNodeAgent: true
        snapshotsEnabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: v1
kind: Namespace
metadata:
  name: velero

---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
stringData: 
  cloud: |
    [default]
    aws_access_key_id=minioadmin
    aws_secret_access_key=minioadmin123