apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" 
spec:
  project: default
  source:
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    targetRevision: 5.3.0
    chart: velero
    helm:
      values: |
        # --- THÊM PHẦN NÀY VÀO ---
        kubectl:
          image:
            repository: docker.io/bitnami/kubectl
            tag: "1.30.0" # Hoặc "1.29.0". Ép dùng tag có thật thay vì 1.34
        # -------------------------
        
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: http://minio-service.default.svc.cluster.local:9000
        credentials:
          existingSecret: cloud-credentials
        deployNodeAgent: true
        snapshotsEnabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true