apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
      - name: ai-container
        image: dthieudocker/ai-service:09d509dd7e6693a07e17dcd32b102e1fd6cef41a
        ports:
        - containerPort: 8080