apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
        - name: ai-container
          image: dthieudocker/ai-service:40a10d4c415ec5a7d160d6d1722ae395863b86cd
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dio.netty.resolver.dns.preferIpv4=true"
            - name: MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED
              value: "false"
