apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-activity-deployment
  labels:
    app: user-activity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-activity-api
  template:
    metadata:
      labels:
        app: user-activity-api
      annotations:
        backup.velero.io/backup-volumes: backup-storage
    spec:
      containers:
      - name: user-activity-container
        image: dthieudocker/user-activity-service:aa02994538122a381280e2f9d285adf876cbbdc8
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: backup-storage
          mountPath: /app/backups
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: shared-backup-pvc