apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
      annotations:
        backup.velero.io/backup-volumes: backup-storage
    spec:
      serviceAccountName: admin-sa # <--- B?N CH? C?N THÊM DÒNG NÀY
      containers:
      - name: admin-container
        image: dthieudocker/admin-service:86f9adf01043d31b4b92d52cd636febd5ce0178d
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: backup-storage
          mountPath: /app/backups
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: shared-backup-pvc