apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: "^3"
    chart: k8s-monitoring
    helm:
      values: |
        cluster:
          name: k3s-cluster  # Giữ nguyên hoặc đổi tùy ý bạn
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net./api/prom/push
            auth:
              type: basic
              username: "3013810"
              password: glc_eyJvIjoiMTY4NjI1NSIsIm4iOiJzdGFjay0xNTQ0NzkxLWludGVncmF0aW9uLWszcy1tb25pdG9yaW5nLXRva2VuLWszcy1tb25pdG9yaW5nLXRva2VuIiwiayI6Im1qODVVMkE1YjF3UjM2MlZtMXpCcDJQQyIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTEifX0=
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-020.grafana.net./loki/api/v1/push
            auth:
              type: basic
              username: "1502580"
              password: glc_eyJvIjoiMTY4NjI1NSIsIm4iOiJzdGFjay0xNTQ0NzkxLWludGVncmF0aW9uLWszcy1tb25pdG9yaW5nLXRva2VuLWszcy1tb25pdG9yaW5nLXRva2VuIiwiayI6Im1qODVVMkE1YjF3UjM2MlZtMXpCcDJQQyIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTEifX0=
        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: k3s-cluster
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net./api/prom
          kepler:
            enabled: true
        clusterEvents:
          enabled: true
        podLogs:
          enabled: true
        alloy-metrics:
          enabled: true
          alloy:
            extraEnv:
              - name: CLUSTER_NAME
                value: k3s-cluster
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-013.grafana.net
            auth:
              type: basic
              username: "1544791"
              password: glc_eyJvIjoiMTY4NjI1NSIsIm4iOiJzdGFjay0xNTQ0NzkxLWludGVncmF0aW9uLWszcy1tb25pdG9yaW5nLXRva2VuLWszcy1tb25pdG9yaW5nLXRva2VuIiwiayI6Im1qODVVMkE1YjF3UjM2MlZtMXpCcDJQQyIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTEifX0=
        alloy-singleton:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-013.grafana.net
            auth:
              type: basic
              username: "1544791"
              password: glc_eyJvIjoiMTY4NjI1NSIsIm4iOiJzdGFjay0xNTQ0NzkxLWludGVncmF0aW9uLWszcy1tb25pdG9yaW5nLXRva2VuLWszcy1tb25pdG9yaW5nLXRva2VuIiwiayI6Im1qODVVMkE1YjF3UjM2MlZtMXpCcDJQQyIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTEifX0=
        alloy-logs:
          enabled: true
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-013.grafana.net
            auth:
              type: basic
              username: "1544791"
              password: glc_eyJvIjoiMTY4NjI1NSIsIm4iOiJzdGFjay0xNTQ0NzkxLWludGVncmF0aW9uLWszcy1tb25pdG9yaW5nLXRva2VuLWszcy1tb25pdG9yaW5nLXRva2VuIiwiayI6Im1qODVVMkE1YjF3UjM2MlZtMXpCcDJQQyIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTEifX0=
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true