apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
      containers:
      - name: workflow-container
        image: dthieudocker/workflow-service:af495ea1d0c1bf36808b8b677e6a2396e368ffdc
        ports:
        - containerPort: 8080